---
- hosts: localhost
  connection: local
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Pull in Site Variables
      include_vars: /tmp/site_vars.yml

    - name: Setup Avi Site
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_config_file: site_config.yml

    - name: Add AKO Helm Repo
      kubernetes.core.helm_repository:
        name: ako
        repo_url: https://projects.registry.vmware.com/chartrepo/ako

    - name: Create Values file for AKO Deployment
      template:
        src: ako-values.j2
        dest: /tmp/values.yaml

    - name: Deploy AKO
      kubernetes.core.helm:
        name: ako
        chart_ref: ako
        release_namespace: avi-system
        create_namespace: yes
        update_repo_cache: yes
        values: "{{ '/tmp/values.yaml' | from_yaml }}"
        kube_context: "{{ eks_cluster_context }}"
