avi_config:           
  cloud:
    - name: AWS
      vtype: CLOUD_AWS
      aws_configuration:
        use_iam_roles: true
        route53_integration: true
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        zones: 
          - mgmt_network_uuid: "{{ private_subnet_1_uuid }}"
            mgmt_network_name: "{{ private_subnet_1_name }}"
            availability_zone: "{{ private_subnet_1_az }}"
          - mgmt_network_uuid: "{{ private_subnet_2_uuid }}"
            mgmt_network_name: "{{ private_subnet_2_name }}"
            availability_zone: "{{ private_subnet_2_az }}"
  serviceenginegroup:
    - name: Default-Group
      cloud_ref: /api/cloud?name=AWS
      instance_flavor: t3.medium
  errorpageprofile:
    - name: Custom-Error-Profile
      error_pages:
        - index: 0
          enable: true
          match:
            match_criteria: IS_IN
            status_codes:
              - 403
          error_page_body_ref: /api/errorpagebody?name=Custom-Error-Body
  errorpagebody:
    - name: Custom-Error-Body
      error_page_body: "<!DOCTYPE html>\n<html>\n<head>\n<title>Access Denied</title>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n<meta charset=\"UTF-8\">\n<link rel=\"stylesheet\" href=\"style.css\">\n<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n</head>\n<body>\n<div class=\"w3-display-middle\">\n<h1 class=\"w3-jumbo w3-animate-top w3-center\"><code>Access Denied</code></h1>\n<hr class=\"w3-border-white w3-animate-left\" style=\"margin:auto;width:50%\">\n<h3 class=\"w3-center w3-animate-right\">You dont have permission to view this site.</h3>\n<h3 class=\"w3-center w3-animate-zoom\">🚫🚫🚫🚫</h3>\n<h6 class=\"w3-center w3-animate-zoom\">error code:403 forbidden. request id: $request_id ; application name: $vs_name </h6>\n</div>\n</body>\n</html>\n"
      format: ERROR_PAGE_FORMAT_HTML